# ATTENTION: Pour que l'autoscaling CPU fonctionne, votre déploiement 'api' 
# doit IMPÉRATIVEMENT avoir la section 'resources: requests:' définie 
# (ce qui devrait être le cas dans votre manifeste S4).

# 1. Horizontal Pod Autoscaler (HPA) pour l'API (3 pts)
# Objectif : Mettre à l'échelle si le CPU dépasse 60%
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: workshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Cible 60% d'utilisation CPU
---
# 2. Pod Disruption Budget (PDB) pour l'API (2 pts)
# Objectif : Assurer qu'au moins 2 Pods restent disponibles lors des opérations de maintenance.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  namespace: workshop
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api