# Fichier: S4/manifests.yaml - Version corrigée pour éviter le 403 Forbidden

---
# 1. Namespace de travail
apiVersion: v1
kind: Namespace
metadata:
  name: workshop

---
# 2. ConfigMap pour le front
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: workshop
data:
  BANNER_TEXT: "Hello M2 IR"

---
# 3. Secret pour l'API
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: workshop
stringData:
  DB_USER: app
  DB_PASS: changeMe123

---
# 4. Deployment du Front
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        # CORRECTION ICI : Utilisation de l'image Docker Hub publique
        image: nginxdemos/hello:plain-text
        env:
        - name: BANNER_TEXT
          valueFrom:
            configMapKeyRef:
              name: front-config
              key: BANNER_TEXT
        ports:
        - name: http
          containerPort: 80

---
# 5. Service du Front
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: workshop
spec:
  selector:
    app: front
  ports:
  - port: 80
    targetPort: http

---
# 6. Deployment de l'API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kennethreitz/httpbin
        ports:
        - name: http
          containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS

---
# 7. Service de l'API
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: workshop
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: http

---
# 8. ClusterIssuer self-signed (TLS)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
# 9. Ingress pour le routage L7
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: workshop
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned
spec:
  tls:
  - hosts: ["workshop.local"]
    secretName: web-tls
  rules:
  - host: workshop.local
    http:
      paths:
      - path: /front
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80