# Fichier: S4/s4-workloads.yaml

---
# 1. Deployment du Front (consomme la ConfigMap)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: workshop
spec:
  [cite_start]replicas: 2 [cite: 48]
  selector: { matchLabels: { app: front } }
  template:
    metadata: { labels: { app: front } }
    spec:
      containers:
      - [cite_start]name: front [cite: 54]
        [cite_start]image: ghcr.io/nginxdemos/hello:plain-text [cite: 55]
        [cite_start]ports: [{ name: http, containerPort: 80}] [cite: 60]
        env:
        - [cite_start]name: BANNER_TEXT [cite: 57]
          # L'application consomme la valeur de la ConfigMap 'front-config'
          [cite_start]valueFrom: { configMapKeyRef: { name: front-config, key: BANNER_TEXT}} [cite: 58, 59]

---
# 2. Service du Front
apiVersion: v1
kind: Service
metadata: 
  name: front
  namespace: workshop
spec:
  [cite_start]selector: { app: front } [cite: 65]
  [cite_start]ports: [{ port: 80, targetPort: http}] [cite: 66]

---
# 3. Deployment de l'API (consomme le Secret)
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: workshop
spec:
  [cite_start]replicas: 2 [cite: 70]
  [cite_start]selector: { matchLabels: { app: api } } [cite: 71]
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - [cite_start]name: api [cite: 74]
        [cite_start]image: kennethreitz/httpbin [cite: 75]
        [cite_start]ports: [{ name: http, containerPort: 80}] [cite: 76]
        env:
        - [cite_start]name: DB_USER [cite: 78]
          # L'application consomme la valeur du Secret 'app-secrets'
          [cite_start]valueFrom: { secretKeyRef: { name: app-secrets, key: DB_USER } } [cite: 79]
        - [cite_start]name: DB_PASS [cite: 79]
          [cite_start]valueFrom: { secretKeyRef: { name: app-secrets, key: DB_PASS}} [cite: 80]
          
---
# 4. Service de l'API
apiVersion: v1
kind: Service
metadata: 
  name: api
  namespace: workshop
spec:
  [cite_start]selector: { app: api } [cite: 85]
  [cite_start]ports: [{ port: 80, targetPort: http}] [cite: 86]